### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Samirkhairati** [Samirkhairati/monster#1]
### Project Setup
- [x] Create basic HTML page with minor CSS
- [x] Running project on local web server
- [x] Add Phaser 3 library
- [x] Create a basic Phaser 3 game instance
- [x] Add jsconfig to get Phaser 3 types and IntelliSense

### Game Project Assets
- [x] Download game assets and add to project
- [x] Show links to where assets can be found

### Battle System
- [x] Load game assets
- [ ] Create battle scene layout
- [ ] Create dialog menu
- [ ] Create option menu
- [ ] Create monster attack move list
- [ ] Handle player input
- [ ] Code optimization - move logic to components
  - [ ] Create health component
  - [ ] Create background component
  - [ ] Create monster components
- [ ] Adding basic attack logic
- [ ] Taking damage and monster knock out
- [ ] Battle state machine
  - [ ] What is a finite state machine
  - [ ] Review the battle states and what each one represents
  - [ ] Implement each state
  - [ ] Add item, flee, and monster states
  - [ ] Player input improvements
- [ ] Battle scene polish
  - [ ] Text animations
  - [ ] Monster animations
  - [ ] Skip animations
  - [ ] Attack animations
  - [ ] Scene transitions
  - [ ] Custom fonts

### World Scene
- [ ] Load level background
- [ ] Create player
- [ ] Handle player input
- [ ] Camera movement
- [ ] Handle grid-based movement
- [ ] Handle collisions
- [ ] Add wild monster encounter logic
- [ ] Store player position in data manager

### Level Development with Tiled
- [ ] Basic level design concepts
- [ ] Add collision layer
- [ ] Add custom types to Tiled
- [ ] Add game objects
- [ ] Add NPCs
- [ ] Exporting level images and JSON

### World Scene Part 2
- [ ] Add interactive game objects
- [ ] Dialog UI component
- [ ] Add NPCs
- [ ] Add NPC dialog
- [ ] Add NPC movement

### Title Screen
- [ ] Create basic title screen
- [ ] Add options menu
- [ ] Save & loading options
- [ ] Connecting option data to battle scene

### Bug Fixes Part 1
- [ ] Battle scene - health bar value when battle starts
- [ ] Health bar - animation when value of delay is provided
- [ ] Battle scene - at battle start player can provide input
- [ ] World scene - player movement, handle when only sprite direction changes

### Tools Part 1
- [ ] Using Tweakpane for testing
  - [ ] Tweakpane basics
  - [ ] Positioning game objects
  - [ ] Monster attacks
  - [ ] Animations
- [ ] Util function for moving game objects

### Saving & Loading
- [ ] Add game menu with option to save game
- [ ] Update menu scene with continue option to load game
- [ ] On new game, we should reset the player data (pos, monsters, etc)

### Monster Party & Monster Detail Scenes
- [ ] Create monster party scene
- [ ] Allow player to select a monster in the scene
- [ ] Create monster detail scene
- [ ] Connect monster detail scene to monster party scene
- [ ] Add game menu option for viewing monster party scene

### Inventory
- [ ] Create class for items and inventory
- [ ] Create UI screen for viewing items
- [ ] Update menu to have view bag option
- [ ] Update data manager to allow saving of inventory items
- [ ] Update UI screen to allow player to use items

### Battle Scene Part 2
- [ ] Using items
- [ ] Running away
- [ ] Enemy random attack
- [ ] Player faint
- [ ] Attacking order
- [ ] Update data manager to persist monster data and current stats
- [ ] Dynamic monster data based on player party and encounter

### Audio
- [ ] Adding background music
- [ ] Adding battle music
- [ ] Adding attack effects
- [ ] Connecting audio options to settings

### World Scene Part 3
- [ ] Advanced wild monster encounter logic
- [ ] Buildings
- [ ] Items in the field
- [ ] NPC event data structure
- [ ] Respawn next to NPC

### Leveling & Experience
- [ ] Review math for leveling and exp gain
- [ ] Update monsters JSON file and types to include exp info
- [ ] Add new assets for exp bar
- [ ] Refactor HP bar into reusable class
- [ ] Update battle scene to display exp bar
- [ ] Update monster details scene to display exp bar
- [ ] Gain exp when battle is over
  - [ ] Add new battle state for tracking
  - [ ] New leveling utils for updates
  - [ ] Update monster classes to support
  - [ ] Update battle menu UI to have word wrap

### Multiple Monsters
- [ ] Load new assets
- [ ] Battle scene
  - [ ] Battle monster class
    - [ ] Add support for switching monster details
  - [ ] Player battle monster class
    - [ ] Add support for switching monster details
    - [ ] Update death animation to hide health bar components
  - [ ] Battle menu
    - [ ] Update switch monster logic to align with flee attempt
  - [ ] Battle scene
    - [ ] New state for switching monsters and scene resume logic
    - [ ] Update existing states to support switching active monster
    - [ ] Update existing logic for switching monster when active monster is knocked out
    - [ ] Update logic tied to exp gain and message ordering
    - [ ] Add UI to show number of monsters in party
  - [ ] Monster party scene
    - [ ] Add support for selecting monster for switching active monster during battle
- [ ] World scene
  - [ ] Refactor world menu into reusable component
  - [ ] Create confirmation sub-menu
  - [ ] Switch monsters positions in party
  - [ ] Release monster into the wild

### Possible Future Content
- [ ] Cutscenes
- [ ] In-game events and tracking
- [ ] Shops
- [ ] Battle NPCs
- [ ] Monster encyclopedia
- [ ] Monster league/gyms
